### PR TITLE
Support for net standard 1.1 (match profile111).

### PR DESCRIPTION
**Pull request by roubachof**
Deleted one zombie file.
Added build_package_netstandard.ps1 to build netstandard with msbuild 15.
Added netstandard test library.
Update version to 1.0.3.

### CODE REVIEW

**Comment by roubachof** [comment]
Build is failing on travis cause it doesnt reference msbuild 15 but xbuild.
Since the release of VS for Mac, there is a msbuild 15 implementation for mac os / linux.

**Comment by markmeeus** [comment]
Hi Roubachof,

Thank you for the PR.
I'm having a few more days off work, and mostly away from laptops, but I will look into this next week.

Do you think you could get it to build on travis?

**Comment by roubachof** [comment]
@markmeeus I will try to play with the travis.yml file see if it can use msbuild instead of xbuild.

**Comment by markmeeus** [comment]
Hi, 

I took a closer look at your PR (thanks again btw).

A few remarks:
1: I'm not sure why we need a separate build_package script, can't we build the standard1.1 in the existing build_package script?

2: Obviously, the travis build is broken :-) The travis build does not actually build the package, it is just running the tests. (Most of MarcelloDB is plaform independent, so we can run in on mono).
I'm not sure how to get msbuild working in Travis, but we don't really need to because the complete build has to be done on a Windows Machine any way. (for the 8.1/10 platform stuff). This is the reasoning behind the MarcelloDB.win.sln.
(I build the package manually inside a vm)

So if you add the standard1.1 to that solution and remove it from the main solution, it will get build with the regular build script. (Just need to add the correct files in the package).

3: I haven't been following the .net world as much lately.
I thought it would be as simple as packaging MarcelloDB.dll as the standard1.1 version because profile 111 can be used as standard 1.1. (https://docs.microsoft.com/en-us/dotnet/standard/net-standard) (Check the PCL compatibility part)
If this is the case, we don't even need a separate project, just copy the marcellodb.dll to the appropriate package folder and we're done.

**Comment by roubachof** [comment]
hey mark !

1. we don't need it. It's just that my configuration is not really compatible with your tools pathes. So I created my own (msbuild 15 and nuget).
2. I don't understand why it's failing on Travis. It use latest mono so it should have msbuild 15, and it's "working on my machine" with the command line :/.
3. It's not really that easy cause I also converter the ols csproj to the new one. Also many folks out there haven't the correct Visual Studio version supporting .net standard. So I think it's better to have 2 csproj for now. And later just you can just delete the PCL csproj.

**Pull request closed without merging**
